name: Label Config

on:
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v2
        with:
          yaml_file: .github/labels.yml
          skip_delete: true
          dry_run: false
          exclude: |
            help*
            *issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
